### ISSUE TITLE
[ci/cd] add remote cli test

### ISSUE THREAD

**Issue by deer** [netzo/netzo#102]
Followup to https://github.com/netzo/netzo/issues/96, since the PR got too big. Pulling out the second item:
* invoke the remote initialize script. need a better way to determine where the script is running from. ideally it would invoke itself remotely, i.e. use the latest code from either the current PR or main, but in a remote fashion, e.g. https://raw.githubusercontent.com/deer/netzo/56ec38dd1aae53bdeb4751f8c16d0e46a31c7ca7/lib/cli/netzo.ts. The CLI should accept a "debug" flag to log its location, so we can more properly determine this. Additionally, because it's only for internal use, we won't document it or expose it in the help. Because this is just a testing thing, I'll add this as part of this issue.

**Comment by miguelrk** [comment]
**Update:** just released https://github.com/netzo/netzo/releases/tag/0.4.33 and https://github.com/netzo/netzo/issues/86 is now resolved.

For tracking, what's pending to close this issue is (as per point 3 in [this comment](https://github.com/netzo/netzo/pull/109#issuecomment-1937020787)):

> modify the "remote CLI execution" test I've added here. What I'll do is grab the latest published version and change the test to invoke deno run -A hhttps://deno.land/x/netzo@${latestVersion}/cli/netzo.ts init minimal --dir ${tmpDirName} instead of the hardcoded value I currently have.
