### ISSUE TITLE
[chore] remove remaining hardcoded version references

### ISSUE THREAD

**Issue by deer** [netzo/netzo#114]
A followup to https://github.com/netzo/netzo/issues/86. We should go after the remaining two usages of version numbers in the code and get rid of them:
* https://github.com/netzo/netzo/blob/804c6f7fb129f5758aa1bb970730de0c7b8712a1/lib/plugins/unocss/csr/bundle.task.ts#L18
* https://github.com/netzo/netzo/blob/804c6f7fb129f5758aa1bb970730de0c7b8712a1/lib/plugins/unocss/plugin.ts#L165

Using hardcoded versions makes it impossible to properly test these, since any changes made locally won't be reflected, because it's always referencing a published version.

**Comment by miguelrk** [comment]
Agreed! Nice head start now that you've got this to only 2 occurrences...
