### ISSUE TITLE
[deployments] unexpected behavior in deployment history

### ISSUE THREAD

**Issue by gabrielromk** [netzo/netzo#77]
I deployed the Netzo handbook, and upon reviewing the deployment history, it became apparent that it was registering more than 10 deployments, despite my lack of intention to do so.

Symptoms:
- [x] Deployment time-stamps not updating in platform?
- [x]  Unsuccessful deployments due to API key issues, suggesting a potential platform-side error.

![Screenshot 2024-01-11 10 49 14 PM](https://github.com/netzo/netzo/assets/71981952/e22d6c9f-5d9a-4582-941c-008b8682c754)

**Comment by gabrielromk** [comment]
I tried redeploying and still facing same issues, but apparently 'something' is deploying to the platform (not the app, changes are not reflected in preview)
![Screenshot 2024-01-11 10 55 40 PM](https://github.com/netzo/netzo/assets/71981952/86cf9632-f93f-4523-8ec4-a4f3f507d0e4)
![Screenshot 2024-01-11 10 56 02 PM](https://github.com/netzo/netzo/assets/71981952/297535e7-0688-4c50-8d6e-46567d122dd1)

**Comment by gabrielromk** [comment]
@miguelrk the issue is that I had no default api key in the general settings of the project.
![Screenshot 2024-01-11 10 56 02 PM](https://github.com/netzo/netzo/assets/71981952/6d1e5406-0598-48b6-aff8-5dee3e7ce440)


For it to be reflected in the platform I had to refresh, it was caching

**Comment by gabrielromk** [comment]
@miguelrk deployment "successful" but changes aren't reflected (layout)

localhost:
![Screenshot 2024-01-11 11 05 54 PM](https://github.com/netzo/netzo/assets/71981952/c9fea016-ad2b-4ae9-8cc6-7175e61e4eda)

production:
![Screenshot 2024-01-11 11 05 38 PM](https://github.com/netzo/netzo/assets/71981952/c8afec07-0497-44fb-bb29-7e7816ce02a5)

**Comment by miguelrk** [comment]
These issues should be resolved by now. Closing...
