### ISSUE TITLE
[framework] unexpected behavior with layout

### ISSUE THREAD

**Issue by gabrielromk** [netzo/netzo#78]
when I pin an object to the left (`fixed left-0`) it covers netzos side-nav
`
            <nav class="fixed left-0 h-full w-18rem bg-white shadow-md overflow-y-auto z-50 hidden md:block px-4">
              <Sidebar
                departmentLinks={page.departmentLinks}
                selectedDepartment={page.department}
              />
`

![Screenshot 2024-01-11 11 17 31 PM](https://github.com/netzo/netzo/assets/71981952/22069470-ecaa-4ac7-9119-2fb0a4857bf3)

**Comment by miguelrk** [comment]
This is just how CSS works, nothing to do here. You can always pin something taking the nav width into account, for example, using `fixed left-[300px]` instead of `fixed left-0`. Closing...
