### ISSUE TITLE
[databases] personal database empty

### ISSUE THREAD

**Issue by gabrielromk** [netzo/netzo#80]
I forked the template and seeded the database, however, I can't see any entries in the platform even though it is working properly.

**Comment by miguelrk** [comment]
@gabrielromk it's important to note the different connections `Deno.openKv` can establish (local and remote). See the [API reference](https://deno.land/api@v1.39.4?s=Deno.openKv&unstable=) for more details:

![image](https://github.com/netzo/netzo/assets/18708856/db343502-d173-4619-92a3-be68e9162461)

That being said, its different if you open

1. the default local database via `await Deno.openKv()`
2. a remote database in netzo via `await Deno.openKv("https://api.deno.com/databases/<database-id>/connect")`

Closing this for now.
